services:
  react-app:
    build: ./client/vite-auth-template-project
    ports:
      - 3000:3000
    env_file:
      - .env
    stdin_open: true # start the container on interctive mode
    tty: true
  
  express-app:
    build: ./server
    ports:
      - 8080:8080
    environment:
     - MONGO_DB_USERNAME=${MONGO_ADMIN_USER}
     - MONGO_DB_PWD=${MONGO_ADMIN_PASS}
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USER}
     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASS}
    volumes:
      - mongo-data:/data/db  # Volume for MongoDB data persistence

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ADMIN_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ADMIN_PASS}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

volumes:
  mongo-data:
